### ISSUE TITLE
[Question] Would the qml sandbox receive the events like keyboard?

### ISSUE THREAD

**Issue by nomiuo** [SavenkovIgor/QmlSandboxExtension#16]

**Comment by SavenkovIgor** [comment]
Interesting question. Weirdly I completely missed this use case)
 I think I can check it and try to retranslate vscode keyboard events if possible

**Comment by nomiuo** [comment]
Sorry, maybe I made a mistake that I did not focus the sandbox tab.
I just cannot recurrent after refreshing the tab. It works fine now!
