### ISSUE TITLE
[Bug] After running a while, a memory error happens.

### ISSUE THREAD

**Issue by nomiuo** [SavenkovIgor/QmlSandboxExtension#18]
I just change the code and the sandbox tab will sync.
Afther a while, it is broken and showing the text below:
``` text
Qt for WebAssembly: QtWasmTemplate
Application exit (RuntimeError: memory access out of bounds)
```

**Comment by SavenkovIgor** [comment]
🤔 looks like wasm error.
Maybe I can just refresh WebView, when catch this. Or try to catch memory leak somehow
https://stackoverflow.com/questions/73829866/runtimeerror-memory-access-out-of-bounds-in-wasm
